### ISSUE TITLE
Font icons not working

### ISSUE THREAD

**Issue by welcoMattic** [adi1090x/rofi#10]
Hi, thanks for your massive work on all of these themes!

I try to make the powermenu applet works, but there's no icon. I installed font properly (Comfortaa and Hurmit) from pacman. I tried your solution described here https://github.com/adi1090x/rofi/issues/3#issuecomment-600838253, but it still not working.

Fonts are working properly in my Font Manager but not in the rofi.
To test what is the problem I tried to replace icons in powermenu.sh by letters, and fonts in powermenu.rasi by basic Arial. I ran the script and it still no character (icon or letter), just blank elements.

Thanks for your help

**Comment by ferreiramx** [comment]
I have the same issue. It was fixed by the same thing suggested in https://github.com/adi1090x/rofi/issues/3#issuecomment-605427180 manually installing release 1.5.4 of Rofi. Now all the icons and fonts work properly.
