### ISSUE TITLE
[Garuda-Linux] After latest system upgrade, the powermenu entries are shifted

### ISSUE THREAD

**Issue by RandomLegend** [adi1090x/rofi#101]
![image](https://user-images.githubusercontent.com/38812603/185581370-f504aa22-7e42-4eb2-8852-cac51d5e79d0.png)

In the powermenu, all the entries are shifted up. This occurs on all the 6 powermenu types. When they only have icons, then these icons are shifted up aswell.

I didn't change anything on the config before upgrading my system. I tried changing the padding of the box, but it didn't change. Any idea on how to fix this?

![image](https://user-images.githubusercontent.com/38812603/185581886-a83fbb94-ba7b-4e16-919e-16c7420cc9d2.png)

The launcher looks normal however.
Thanks!

**Comment by adi1090x** [comment]
I've already fixed that. it's a upstream bug, fixed there too.

**Comment by RandomLegend** [comment]
Thanks for the fast reply!

However the rofi update is not available for me yet. Will that take some more time? or do i have to do something special?
