### ISSUE TITLE
Filebrowser mode in type 6 launchers hides the sidebar

### ISSUE THREAD

**Issue by 96Octavian** [adi1090x/rofi#108]
While in filebrowser mode, sidebar in the left pane with the buttons for the various modes (APPS, RUN, FILES, WINDOW etc) gets pushed out of the window.  
I think this is because the listbox element holds the message elements which is usually hidden but it's now used to show the current directory, thus resulting in a listbox with 9 lines instead of 8:

![image](https://user-images.githubusercontent.com/7478904/188237299-ab9e4999-9dfa-489b-89ef-c232fa4afa28.png)

Moving the "message" element in the "imagebox" element fixed it enough for me:

    imagebox {
        padding:                     20px;
        spacing:                     20px;
        background-color:            transparent;
        background-image:            url("~/.config/rofi/images/f.png", height);
        orientation:                 vertical;
        children:                    [ "inputbar", "message", "dummy", "mode-switcher">
    }
    
    listbox {
        spacing:                     20px;
        padding:                     20px;
        background-color:            transparent;
        orientation:                 vertical;
        children:                    [ "listview" ];
    }

![image](https://user-images.githubusercontent.com/7478904/188237772-73f9b23e-e24e-4866-a39b-29b021f55353.png)

Note that I'm using the rofi wayland fork on sway, but I expect this to be unrelated to the wayland fork

**Comment by 2goodAP** [comment]
Hey @96Octavian. It seems that this issue is actually quite related to the wayland fork. I was using __1.7.5+wayland1__ version of `rofi` and I encountered this exact issue. Then I switched over to upstream __1.7.5__ and the theme worked just fine. I even tried with default config and the behavior was only reproducible in the wayland version.
