### ISSUE TITLE
Apps icons is very small in app launcher

### ISSUE THREAD

**Issue by Andrmist** [adi1090x/rofi#11]
In rofi app launcher all icons are small
![image](https://user-images.githubusercontent.com/13292397/78685690-c88c0c80-78fa-11ea-9b34-b19d4a18e992.png)

**Comment by adi1090x** [comment]
[Install](https://github.com/davatorium/rofi/blob/next/INSTALL.md#install-a-checkout-from-git) the latest rofi version (bleeding edge)
