### ISSUE TITLE
Missing app launcher theme

### ISSUE THREAD

**Issue by VijayLalwani** [adi1090x/rofi#13]
First of all, thanks for compiling such great themes its awesome.

In readme there is a app launcher theme named simple dark which is missing i guess? can you add it? i would like to use that theme.

**Comment by adi1090x** [comment]
Edit the [file](https://github.com/adi1090x/rofi/blob/master/launchers-git/kde_simplemenu.rasi) and uncomment the breeze dark color, or the black one.
