### ISSUE TITLE
Problem with config.rasi

### ISSUE THREAD

**Issue by Pazos-956** [adi1090x/rofi#149]
When i start rofi it shows:

Parser eror: syntax error, unexpected invalid property name, expecting "property separator( ' : ' )"

Location: line 41 column 6 to line 41 column 8.

File .config/rofi/config.rasi

**Comment by tonmoy998** [comment]
same here I have problem in line 54 and column num 6 when I open rofi it shows error.

**Comment by TDGalea** [comment]
Found it: look for `run,drun` and replace it with `run-drun`

Pretty silly error tbh.

**Comment by Pazos-956** [comment]
> Found it: look for `run,drun` and replace it with `run-drun`
> 
> 
> 
> Pretty silly error tbh.

I sae this in another report, i change it already so its not the problem but i realized that with apt the version installed is 1.5 instead of 1.7, so that might be the problem here

**Comment by TDGalea** [comment]
Yeah I caught that you changed it as well. Clearly apt being behind as
usual.
It's a single character anyway, so easy enough to fix if you find it.
Hopefully anyone installing Rofi should be able to find this.

**Comment by 74O** [comment]
Hi! I installed this using the guide on this link [https://github.com/adi1090x/rofi] by cloning from git. This issue seems to be still present. Already fixed it thanks to @TDGalea 💯

**Comment by hoshiya4522** [comment]
Had the same error..

fixed it by replacing
```
        /*---------- Fallback Icon ----------*/
        run,drun {
                fallback-icon: "application-x-addon";
        }
```
with
```
        /*---------- Fallback Icon ----------*/
        run {
                fallback-icon: "application-x-addon";
        }

        drun {
                fallback-icon: "application-x-addon";
        }

```
