### ISSUE TITLE
`uptime -p` is not standard

### ISSUE THREAD

**Issue by M-Gregoire** [adi1090x/rofi#15]
Hi,

First of all, thank you for your repositories, they are awesome!

I noticed you use `uptime -p` in you powermenu. However, the `-p` option does not seems really wide-spread and generate the following error on my OS: `uptime: invalid option -- 'p'`.

Looking at the man page, https://linux.die.net/man/1/uptime the `-p` option isn't mentioned. Do you use a specific version of uptime? 

Otherwise, would you be ready to consider a more standard way to display this information?

**Comment by TheToto** [comment]
On ArchLinux and Ubuntu 18.04, `update -p` is "pretty"
```
       -p, --pretty
              show uptime in pretty format
```
```
$ uptime   
 01:17:53 up 2 days, 10:17,  1 user,  load average: 0,71, 0,91, 1,17
```
```
$ uptime -p
up 2 days, 10 hours, 17 minutes
```

**Comment by adi1090x** [comment]
As @TheToto mentioned, `-p` or `--pretty` option works on almost every distro. @M-Gregoire which distro you are using?

**Comment by M-Gregoire** [comment]
Thank you for your answer.
I use NixOS which uses `uptime` from `GNU coreutils` while, Ubuntu, ArchLinux and a bunch of other distributions take `uptime` from `procps` which explains the lack of the `-p` option.
TIL they are different `uptime` executable from different packages!

It will probably be easier to fix this on my end by replacing the uptime executable so feel free to close this issue; I'll leave it open just in case you want to make a change.

Thanks again for all you different repos, my desktop is much more pleasing to my eyes now :smile:
