### ISSUE TITLE
Getting Rofi's Default theme after installing

### ISSUE THREAD

**Issue by ShinsuSenju** [adi1090x/rofi#166]
Getting default theme in rofi. im using manjaro with hyprland

rofi version : Version: 1.7.5+wayland2-227-gbe7c088e
![image](https://github.com/adi1090x/rofi/assets/63202411/9bdd6ed4-bcfb-480b-908c-93e5a3c77ffb)

**Comment by reyandabreo** [comment]
Navigate to  config file  **~/.config/rofi/config.rasi**       

and on the last line of the file add :
 `@import "~/.config/rofi/launchers/type-1/style-1.rasi"  `   

Change the type-1 and style-1 as your need.
