### ISSUE TITLE
Scaling problem - excess window size and icons off-centre

### ISSUE THREAD

**Issue by abers** [adi1090x/rofi#17]
I am running rofi version 1.5.4 on Ubuntu 19.10 using i3-gaps. My screen resolution is 1920x1200.

When running the scripts the windows are too large (similar to #2 ) and the icons are off-centre. I can fix the window size going through the files and changing the height and width percentages but I cann't figure out how to fix the icon centring. 

![scaling issue](https://i.imgur.com/DmxuSm5.png)

**Comment by adi1090x** [comment]
That's the issue with different screen resolution, you can edit the respective theme file, adjust padding in line 27.
I'll update these configs to handle different screen resolution later.

**Comment by teixeiras** [comment]
yeah, I'm changing all values for my pc, you should use absolute values (> 100) instead percentage.

**Comment by garret** [comment]
> yeah, I'm changing all values for my pc, you should use absolute values (> 100) instead percentage.

I also had to edit the padding values manually but are you sure you can enter percentage values? I tried and rofi did not start up. Maybe it needs 'pt' values unfortunately. 

It is especially a problem for me since I have three screens each with a different resolution :/

**Comment by adi1090x** [comment]
@garret @teixeiras @abers 
Support for multiple screen resolutions is added now, try again.
