### ISSUE TITLE
Use Hidden Search Terms via rofi's Meta option

### ISSUE THREAD

**Issue by boi4** [adi1090x/rofi#18]
First of all, thanks for the great scripts.

A downside of using icons for the selection options, that you have to use the arrow keys to select an option.
The rofi version on github already features hidden search terms (see: https://github.com/davatorium/rofi/pull/1052). They are added by sending some more information behind a null byte to rofi's stdin. 

It would be great if one could include hidden search terms to improve selectability of options.

For example, typing "poweroff" (or some fuzzy search part of it) should select the poweroff button in the power menu.

If you like the idea, I can start working on it and make a pull request.

**Comment by adi1090x** [comment]
Will consider that. If you're still up for that PR, Be my guest.
