### ISSUE TITLE
Icons not displayed

### ISSUE THREAD

**Issue by yasanthachamara** [adi1090x/rofi#19]
Hi,

I'm an Arch user and I've installed all the fonts in the repo. But I still cannot see the icons when I run any script. Please find below screenshot. I tried changing the 'icon-font' to a different nerd font, but the issue is still there.

![Volume-no-icon](https://user-images.githubusercontent.com/33784749/81467471-74749080-91f6-11ea-9b0d-fa2d093dc69d.png)

Any help is appreciated.

Thanks,
Yasantha

**Comment by adi1090x** [comment]
Use stable rofi version (from official Arch repo) not the AUR version.

**Comment by yasanthachamara** [comment]
> Use stable rofi version (from official Arch repo) not the AUR version.

Thank you. It's working fine now.
