### ISSUE TITLE
Feather icons not appearing on rofi-git power menus

### ISSUE THREAD

**Issue by alex-bellon** [adi1090x/rofi#21]
I installed the power menus, and currently when I try to launch the menu, none of the icons appear despite the fact that I have the `feather` font installed.

![powermenu](https://user-images.githubusercontent.com/24237402/81743728-c1ab6900-9467-11ea-8c04-e3dd73161203.png)

I've tried this with multiple themes but the issue persists on all of them.

**Comment by lougehrig10** [comment]
Font icons should be coming from Hurmit Nerd Font Mono for menus

**Comment by alex-bellon** [comment]
I installed the Hurmit font and it still did not work. 

I assumed it was the Feather font because in the `.rasi` files it says:
```
element-text {
	font: "feather 32";
```

It also says in the `README.md` that the only fonts you need for the power menus are Feather and Fantasque.

**Comment by lougehrig10** [comment]
Huh. For me, the README says 

> Comfortaa Used for normal text
Hurmit Nerd Font Mono Used for icons
Feather For icons used in android style sidemenus
Fantasque For App launchers

So you should use Feather if using android style sidemenus, Hurmit otherwise

What rasi file are you looking at? None of the powermenu.rasi files have element-text for me.

**Comment by alex-bellon** [comment]
Sorry, I should have specified that I'm talking about the [rofi-git powermenus](https://github.com/adi1090x/rofi#rofi-powermenu-rofi-git). The `.rasi` files are from [power/full.rasi](https://github.com/adi1090x/rofi/blob/master/power/full.rasi) and the other themes in the same folder.

**Comment by lougehrig10** [comment]
Whats the output of `fc-list | grep feather`?

**Comment by alex-bellon** [comment]
```shell
→ fc-list | grep feather
/usr/share/fonts/feather.woff: feather:style=Regular
/usr/share/fonts/feather.ttf: feather:style=Regular
```

**Comment by adi1090x** [comment]
Use rofi-git

**Comment by alex-bellon** [comment]
Is there any way to check whether I am using `rofi` or `rofi-git`? I'm pretty sure I'm already using `rofi-git` because when I query `pacman -Q rofi` I only get
```
rofi-git 1.5.4.r117.g191f49db-1
```
and nothing about normal `rofi`. I also checked and this is the latest version of `rofi-git`.

**Comment by tusqasi** [comment]
install it from aur. Its mentioned already here https://github.com/adi1090x/rofi#rofi-powermenu-rofi-git

**Comment by alex-bellon** [comment]
It was installed from AUR

**Comment by adi1090x** [comment]
@lougehrig10 @alex-bellon @tusqasi 
Guys, Try Again... Fixed Everything.
