### ISSUE TITLE
icons and title on the same line 

### ISSUE THREAD

**Issue by niccle27** [adi1090x/rofi#25]
Hello !

I'm trying to add a OSX launchpad like app to my configuration. 

I'm running Xmonad on manjaro. And i was quite interested in your launchpad theme for rofi.

as shown here: (https://raw.githubusercontent.com/adi1090x/files/master/rofi/images/launchers_git/6.png)

Though i'm running in some issue. I configured "launcher.sh" to use the "launchpad.rasi" configuration.
Unfortunnately the results isn't fully as expected: 
![2020-08-15-14:08:29_F](https://user-images.githubusercontent.com/28828886/90311968-d5e88180-df00-11ea-99ed-5db958c30a48.png)

Every icon is displayed next to the text and not below the text as shown in your exemple. How can i achieve that ? 
Would there be a way of achieving this ?

On top of that, do you have an idea how i could achieve to swipe the launchpad a bit like in OSX ? 

Thank you a lot for your work. This is amazing !

**Comment by WeAreInsanity** [comment]
I'm also having this issue with the Slingshot launcher.

**Comment by adi1090x** [comment]
@NimbleClint @niccle27 
Fixed it. Try Again.
