### ISSUE TITLE
Bluetooth applet

### ISSUE THREAD

**Issue by jerbaroo** [adi1090x/rofi#26]
First of all thank you for your amazing work!

One of two applets that are missing for my use case (moving from macOS to Linux) is a bluetooth applet. Would be great to be able to connect to my headphones from the status bar.

**Comment by barischrooneyj** [comment]
I would be interested in looking into this, but can only do so later in the year.

**Comment by varlevi** [comment]
There is a great implementation of a rofi bluetooth menu that can be found [here](https://github.com/ClydeDroid/rofi-bluetooth). It's open source, so maybe @jerbaroo or @adi1090x could use that as a base for an applet here that would integrate with the other applets in this repo?

**Comment by adi1090x** [comment]
@varlevi Thanks for the reference. I'll add a Bluetooth applet soon.
