### ISSUE TITLE
Very small icons and weird element padding 

### ISSUE THREAD

**Issue by TheLegent27** [adi1090x/rofi#28]
Hello,
Every applet or menu I try to run looks like that.
![](https://i.ibb.co/VQVm3p5/rofi.png)

 I'm running now stable release of rofi(ver. 1.6.0) but I have tried with next branch too. All fonts are installed in `/usr/share/fonts` I guess all my fonts are installed but here is fc-mach output of needed fonts.
```
fc-match 'Hurmit Nerd Font'
Hurmit Medium Nerd Font Complete.otf: "Hurmit Nerd Font" "medium"

fc-match 'Iosevka'
iosevka-regular.ttf: "Iosevka" "Regular"

fc-match 'feather'
feather.ttf: "feather" "Regular"

fc-match 'Fantasque Sans Mono'
FantasqueSansMono_Regular.ttf: "Fantasque Sans Mono" "Regular"

fc-match 'Comfortaa'
Comfortaa-Regular.ttf: "Comfortaa" "Regular"
```
And this problems appear with all applets and menus but launcher is running without a problem. Is there any easy solution to this?

**Comment by mchataway** [comment]
I found the same thing just in the last couple of days since updating to the latest Rofi, I believe they changed how icons are handled in the latest release or some such. Not sure of a solution yet

**Comment by TheLegent27** [comment]
Ok, thank you for the reply and giving me a bit of context here.

**Comment by fatihkaan22** [comment]
I had the same issue, downgraded rofi to version 1.5.4 for now.

**Comment by sarbajit125** [comment]
Me too same problem, will laucher work with rofi 1.5.4

**Comment by TheLegent27** [comment]
Thanks for workaround solution, going to downgrade too. Now should I close this issue or leave it open? Sorry this is actually my first issue so I don't know what should I do.

**Comment by nathan72419** [comment]
Please leave it open

**Comment by JonnyHaystack** [comment]
1.6.0 has a LOT of changes (some breaking) and can be quite a pain to get your config back to looking how it was unfortunately

**Comment by stiliajohny** [comment]
@TheLegent27 
Do you know if there is a plan to fix this ?

**Comment by ChuckD3ath** [comment]
@TheLegent27 
Were you able to fix this by downgrading? This is my first time trying out these rofi scripts and on 1.6, it was working like on your screenshot but after downgrading, no icons are showing at all, just empty small recangles.

I'd really appreciate help on this.
Thank you.

**Comment by sarbajit125** [comment]
> 
> 
> @TheLegent27
> Were you able to fix this by downgrading? This is my first time trying out these rofi scripts and on 1.6, it was working like on your screenshot but after downgrading, no icons are showing at all, just empty small recangles.
> 
> I'd really appreciate help on this.
> Thank you.

Scripts work perfectlyy in 1.5.4 version, If you are sesing small rectangle, then problem with fonts not correctly installed. Each Script has it own font so make sure you install them correctly. Siji fonts may not work properly even after correctly installed

**Comment by ChuckD3ath** [comment]
@sarbajit125 
Any tips on how to troubleshoot it? I have looked everywhere and installed everything but it wont work :(

**Comment by sarbajit125** [comment]
> @sarbajit125
> Any tips on how to troubleshoot it? I have looked everywhere and installed everything but it wont work :(

You need to provide more information. Which OS? Which Rofi Version? Which module and which font are installed

**Comment by ChuckD3ath** [comment]
> You need to provide more information. Which OS? Which Rofi Version? Which module and which font are installed

It is Arch Linux, Rofi was downgraded from 1.6.0 to 1.5.4.
I installed everything from requirements and out of all modules, only launcher works properly.

For example power menu is not showing any icons at all in small rectangles. Any idea what icon pack to try reinstalling?

**Comment by TheLegent27** [comment]
@stiliajohny @ChuckD3ath Sorry for late reply but now is my college starting and because covid this is a mess. Anyway simple downgrading does the trick no problem with pre 1.6 version.

**Comment by sarbajit125** [comment]
> 
> 
> > You need to provide more information. Which OS? Which Rofi Version? Which module and which font are installed
> 
> It is Arch Linux, Rofi was downgraded from 1.6.0 to 1.5.4.
> I installed everything from requirements and out of all modules, only launcher works properly.
> 
> For example power menu is not showing any icons at all in small rectangles. Any idea what icon pack to try reinstalling?

which power modules, which fonts are causing  issues

**Comment by ChuckD3ath** [comment]
> > > You need to provide more information. Which OS? Which Rofi Version? Which module and which font are installed
> > 
> > 
> > It is Arch Linux, Rofi was downgraded from 1.6.0 to 1.5.4.
> > I installed everything from requirements and out of all modules, only launcher works properly.
> > For example power menu is not showing any icons at all in small rectangles. Any idea what icon pack to try reinstalling?
> 
> which power modules, which fonts are causing issues

I am trying powermenu.sh and menu_powermenu.sh. I dont know which ones are causing problems lol that's why I'm asking here.
Everything is installed but no icons are showing at all, it's exactly like on @TheLegent27's screenshot but no icons and rectangles are small.

**Comment by TheLegent27** [comment]
@ChuckD3ath I didn't have that issue, but did you try to fc-match all required fonts? I think some icons are from one of this fonts. That's my only idea really.

**Comment by ChuckD3ath** [comment]
Everything is ther like on your original post @TheLegent27 :(

![image](https://user-images.githubusercontent.com/33813588/94996522-770cc380-05a5-11eb-9766-652298fff747.png)

App launcher works perfectly but I guess it's because it uses Papirus icon theme.

**Comment by TheLegent27** [comment]
@ChuckD3ath I can't help here then. After downgrade everything work for me just fine. I'm sorry.

**Comment by guidiamond** [comment]
Same problem here, small icons and small rectangles (i've installed all the required fonts from AUR)

**Comment by Simon-the-Sorcerer** [comment]
I'm currently trying to fix the powermenu in 1.6.0. I've changed `menu-element-padding` to `35px 45px 35px 25px`. This fixes the sizes of the boxes:

![rofi](https://user-images.githubusercontent.com/7312638/95044331-76784800-06df-11eb-93f4-107cc0a2cc2d.png)

My only problem is that the 2nd font (My Nerd Font) isn't loading, although it is installed.

**Comment by ChuckD3ath** [comment]
@Simon-the-Sorcerer Wwell playing with paddings and changing them around fixed it for me too on 1.5.4 but not sure why is it so out of place per default so I will have to change it for every menu I want to use :(

**Comment by JonnyHaystack** [comment]
> I'm currently trying to fix the powermenu in 1.6.0. I've changed `menu-element-padding` to `35px 45px 35px 25px`. This fixes the sizes of the boxes:
> 
> ![rofi](https://user-images.githubusercontent.com/7312638/95044331-76784800-06df-11eb-93f4-107cc0a2cc2d.png)
> 
> My only problem is that the 2nd font (My Nerd Font) isn't loading, although it is installed.

Same happens for me. It's not a problem loading the Hurmit Nerd font, because if you change the text-font to Hermit Nerd the icons look fine but the prompt is the wrong font. Looks like some change to the way the styles are applied? It's only applying the first font it's given. I've tried moving around the font assignment into different blocks but no luck so far.

**Comment by JonnyHaystack** [comment]
Update: _**Success!**_
@Simon-the-Sorcerer You don't have to change the paddings at all. You just need to move the `text-font: @text-font;` line into the `#window {` block, and everything goes back to normal!

Diff:
![image](https://user-images.githubusercontent.com/1266473/96653527-334de400-1331-11eb-8e3e-a52ae0207b37.png)

This small change should fix all of the scripts, so it should be an easy job to fix it for the whole repo. Now we don't need to use the outdated rofi version anymore :smiley:

**Comment by joselevelsup** [comment]
@JonnyHaystack Unfortunately, that didn't work for me. The icons are still small. Even tried applying it to the `#element` but still nothing. I'm still playing around but if I find something, I'll share.

**Comment by adi1090x** [comment]
@JonnyHaystack @Simon-the-Sorcerer @joselevelsup @longErste @stiliajohny 
Fixed everything! Try Again.
