### ISSUE TITLE
Nord Colorscheme

### ISSUE THREAD

**Issue by varlevi** [adi1090x/rofi#29]
I understand that you do not want PRs for color schemes, but I've also noticed there is no Nord color scheme. Seeing as Nord is a very popular color palette, would this be something you consider adding? The official Nord Theme website can be found [here](https://www.nordtheme.com/).

**Comment by adi1090x** [comment]
Arc-Dark is very similar to Nord, however... I'll add nord later.

**Comment by varlevi** [comment]
Thanks. I'll use Arc-Dark for the time being, but look forward to the Nord theme!
