### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by milad-abbasi** [adi1090x/rofi#3]
I can not get the icons to work in my setup.  

![powermenu](https://user-images.githubusercontent.com/20030232/76311888-2111bf00-62e7-11ea-86f2-4c3457910d02.png)  

I have copied Comfortaa folder fonts to both `/usr/share/fonts/TTF` and `~/.local/share/fonts`
And copied `Hurmit` font to `/usr/share/fonts/OTF` and `~/.local/share/fonts` and at the end i ran `fc-cache`.
I would appreciate your help

**Comment by adi1090x** [comment]
try installing fonts again, maybe in **/usr/share/fonts**

**Comment by Grobwiefein** [comment]
Hey,
I had the same issue with no icons in e.g. the apps.sh script. The launcher script worked perfectly with application icons.
I solved it by compiling it from the latest release tag of Rofi (currently 1.5.4 according to Github). Before I always compiled Rofi from the next branch i.e. the bleeding edge version :grin:.
@milad-abbasi Hope this helps solving your problem.

**Comment by milad-abbasi** [comment]
@Grobwiefein Thanks for that, It actually solved the issue, I was using the next branch too.
@adi1090x Would you consider the problem in next branch of rofi?

**Comment by andradei** [comment]
I have rofi 1.5.4 compiled from source and still have this problem. All fonts were installed in ~/.local/share/fonts.

![Screenshot from 2020-04-24 12-26-30](https://user-images.githubusercontent.com/2653546/80245924-cc24d080-8628-11ea-9277-b0c3cc0407a7.png)

**Comment by Thetoto** [comment]
I have the same issue with rofi-git. It seems to be a rofi issue
