### ISSUE TITLE
Misshapen figures in Applets

### ISSUE THREAD

**Issue by JSteven-arch** [adi1090x/rofi#31]
![2020-11-28-111550_1366x768_scrot](https://user-images.githubusercontent.com/58661882/100520360-6c1c7c80-316b-11eb-8d09-7a90447c1e9f.png)
I really love your themes but I have not been able to correct the circles

**Comment by exynil** [comment]
before
```
element-text {
	font:							"feather 64";
    expand:                         true;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    margin:                         6.5% 4% 6.5% 4%;
}
```

after
```
element-text {
	font:							"feather 64";
    expand:                         true;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    margin:                         6.5% 4% 13.0% 4%;
}
```

This is not a good solution, but it works. I will be glad if they offer a better solution. I have doubled the margin on the bottom side.

**Comment by adi1090x** [comment]
Use rofi version **`1.6.0-1`**
