### ISSUE TITLE
font parsing doesnt work

### ISSUE THREAD

**Issue by Xor-nand** [adi1090x/rofi#4]
the font parsing seems to be broken, probably missing the xresources parsing for pango?

**Comment by adi1090x** [comment]
it's a problem with rofi-git(aur) version, have you tried the rofi version from official arch(if you're using it) repo?

**Comment by dmigis** [comment]
Same problem, I tried rofi version from official arch, but in git version I cannot get font parsing work.

**Comment by adi1090x** [comment]
yeah, the applets and menus not working with git version of rofi yet, but i'll work on that soon.
