### ISSUE TITLE
Powermenu cannot log out of openbox

### ISSUE THREAD

**Issue by ynavott** [adi1090x/rofi#41]
After not understanding why the logout function of the powermenu did not log out of the system, I looked into ``powermenu.sh`` and  on line 104, when checking for the ``$DESKTOP_SESSION`` envvar for the logout, the script tries to comapre it to ``"Openbox"``, which seems correct at first but after checking the envvar as it is defined on my system with ``echo $DESKTOP_SESSION`` I saw that the envvar returns ``openbox`` with a small o, and not a capital O. After editing the script with the correct small o, the logout function worked. 

I am not sure if this is only a problem on my machine but I think comparing for both ``Openbox`` and ``openbox`` or somehow ignoring capitalization would be preferable.

**Comment by MoDyPL** [comment]
the same issue with i3

**Comment by ynavott** [comment]
This was apparently fixed by the developer without mentioning anything here, closing.

**Comment by maxice8** [comment]
I made #69 that should fix it, can you test it and give an acknowledgement ?
