### ISSUE TITLE
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN"

### ISSUE THREAD

**Issue by rohitjakhar** [adi1090x/rofi#43]
When i run any .sh file, its show this  error

**Comment by freethinker** [comment]
I'm getting the same error as well.

**Comment by Kstheking** [comment]
hey same error, do we have a fix or suggestion for this

**Comment by rvramesh20** [comment]
same error here

For more information see: man rofi
                 Version: 1.7.0

**Comment by ruteshp21** [comment]
It is because system locales are not set properly.

Please try the following commands, this fixed the issue for me
```
echo "LC_ALL=en_IN.UTF-8" | sudo tee -a /etc/environment
echo "LANG=en_IN.UTF-8" | sudo tee -a /etc/locale.conf
sudo locale-gen
```
Reboot the system and the error wont be displayed
