### ISSUE TITLE
Icons are not displaying 

### ISSUE THREAD

**Issue by abhinav031** [adi1090x/rofi#46]
![B1B8C1DE-3776-4203-B29A-ADF8B7EB5424](https://user-images.githubusercontent.com/73749351/107661130-fd04ed80-6cae-11eb-963f-95b15c64bf13.jpeg)

**Comment by Viibrant** [comment]
I had this same issue but managed to resolve it.

My problem was that I (on Ubuntu) installed Rofi from the repos but they were version 1.5 whereas you need specifically Rofi 1.6.x to get this working. 

I had to uninstall Rofi and compile it myself from source and now it works! Maybe that'll help you?

**Comment by abhinav031** [comment]
Hmm. I’ll try that
