### ISSUE TITLE
broken icon size

### ISSUE THREAD

**Issue by wiliamks** [adi1090x/rofi#49]
![2021-03-09-130116_1920x1080_scrot](https://user-images.githubusercontent.com/52431887/110500433-f3b54800-80d7-11eb-921e-568b6d79dae3.png)

using version 1.5.4 of rofi on a 1920x1080 laptop with bspwm with debian buster.

This is happening with every feature.

**Comment by ayushsherpa111** [comment]
same issue.

**Comment by kajdo** [comment]
same :_(

**Comment by RubioDeLimon** [comment]
same :')

**Comment by hartontw** [comment]
Same issue here, I've tried last version, same thing happens. Small icons in all applets and menus.

**Comment by joeyshi12** [comment]
Same D:

**Comment by adch99** [comment]
This issue still exists for me. I think the problem lies in rofi not taking the `font` parameter in `element-text`. I have tried changing it but it doesn't affect anything. I find no mention of it on the `rofi-theme` man-page either. I am using rofi version 1.5.4 on Ubuntu 20.04.

**Comment by AquaBindi** [comment]
can not meny element set font for rofi version 1.5.4
only set one font.

this theme is 1.6.1 or higher. not support lower version.
please install rofi 1.6.1
