### ISSUE TITLE
How to make blur work?

### ISSUE THREAD

**Issue by d4mr** [adi1090x/rofi#51]
I have the latest rofi 1.6.1 installed. Compton is also installed.

Trying to use the app launcher, with the blur theme in misc, the window background does not get blurred. Is blur supposed to work on its own or do I need to configure Compton?

**Comment by d4mr** [comment]
Got this working, you need to setup your compositor with shadow and blur. This is a good starters config http://duncanlock.net/blog/2013/06/07/how-to-switch-to-compton-for-beautiful-tear-free-compositing-in-xfce/

**Comment by salahmak** [comment]
if anyone is still having this problem, the solution posted above is kinda outdated, and to solve this, first you have to build the git version of [picom](https://github.com/yshui/picom/) from source, and install it, and then set these options:
```
blur:
{
  method = "dual_kawase";
  strength = 4;
}


wintypes:
{
  normal = {blur-background = true;};
  splash = {blur-background = false;};
}

```

and finally run picom with these options:
```
picom --experimental-backends --backend glx 
```

**Comment by AdsonCicilioti** [comment]
My picom work fine with blur and shadows, but rofi misc theme blurry don't work. Full transparent.
