### ISSUE TITLE
[FONT] The search/magnifying glass font is not right

### ISSUE THREAD

**Issue by iletthedogsout69** [adi1090x/rofi#7]
I'm using the latest rofi-git(aur) and the magnifying glass is `88`. I already installed the provided font in /usr/share/fonts/ and the noto-fonts, noto-fonts-extras from arch repo.

![123](https://user-images.githubusercontent.com/61376039/78318249-df4b0000-7596-11ea-9538-1900ad48bb2d.png)

**Comment by adi1090x** [comment]
for the search icon, you need to install the **FantasqueSansMono Nerd Font**
