### ISSUE TITLE
How to change position of applets from bottom right to top right?

### ISSUE THREAD

**Issue by qkweint** [adi1090x/rofi#73]
Great work , I am honestly surprised this isn't included within main rofi already.
I use polybar, and it is located at the top of the screen for aesthetics, however launching applets pops up a window on the bottom right, I tried to look for a way to change this but couldn't find anything.
How do I move the applet window to the top rather than the bottom?

**Comment by tonydero** [comment]
There might be an easier way that I'm missing, but you can at least edit the `~/.config/rofi/applets/applets/configs/<style>/<applet>.rasi` files to change the position.
