### ISSUE TITLE
Themes not installing

### ISSUE THREAD

**Issue by calimari0** [adi1090x/rofi#74]
Ok, this might be really dumb, but I have no idea how to select a particular theme. The README just says that all the themes have been installed, but how do you choose **one** of the themes? I've been trying to set it to misc/blurry for the past few hours, but I can't. Could someone help?

**Comment by calimari0** [comment]
> You must use WM to force the file to run in ~/.config/rofi/launchers/ For i3 it is like this: `bindsym $mod+p exec --no-startup-id ~/.config/rofi/bin/launcher_misc` For awesome so: `awful.key({ modkey }, "p", function() os.execute('~/.config/rofi/bin/launcher_misc') end)`

Thank you, that seems to work! Although, I'm still not able to set a certain theme. I've tried replacing `~/.config/rofi/bin/launcher_misc` with `~/.config/rofi/launchers/misc/blurry.rasi`, `~/.config/rofi/bin/launcher_blurry` and `~/.config/rofi/bin/launcher_misc_blurry`, but those don't seem to work. How do I set it? Also, sorry for the late response :(

**Comment by bitshiftnetau** [comment]
Can you please put this in the docs?
