### ISSUE TITLE
Rofi does not scale well

### ISSUE THREAD

**Issue by issadarkthing** [adi1090x/rofi#8]
![2020-04-03-185503_1920x1080_scrot](https://user-images.githubusercontent.com/50593529/78353645-ff051700-75dc-11ea-894e-35b6d7bea4e3.png)

why rofi does not scale well for me?

**Comment by adi1090x** [comment]
have you installed the **Hurmit Nerd Font Mono**

**Comment by issadarkthing** [comment]
yes 
![image](https://user-images.githubusercontent.com/50593529/78419000-e562de80-7673-11ea-8279-b5ff04d87da5.png)

**Comment by adi1090x** [comment]
Install [This](https://github.com/adi1090x/rofi/blob/master/fonts/HurmitNerdFontComplete_Mono.otf) one.

**Comment by issadarkthing** [comment]
not working. same result

**Comment by adi1090x** [comment]
are you using **rofi-git** from AUR or just `rofi` from official arch repo.

**Comment by issadarkthing** [comment]
rofi from apt

**Comment by adi1090x** [comment]
Solution here : #10
