### ISSUE TITLE
How would I change the size of the element boxes in the powermenu?

### ISSUE THREAD

**Issue by Xyrtur** [adi1090x/rofi#85]
I can only seem to find ways to change the colors, and was able to get the entire powermenu itself to be smaller but the icons and their boxes are still the same size which is far too large. If anyone could point me in the right direction, it would be appreciated

Thank you!

**Comment by adi1090x** [comment]
New Applets And powermenu comming soon.

> Launchers are updated, Check the new config file, written from scratch.
