### ISSUE TITLE
Help: 4k Themes

### ISSUE THREAD

**Issue by cloudsftp** [adi1090x/rofi#86]
Can someone use 1080p directory as reference and create themes for 4k (3840 x 2160) for latest rofi version 1.7.0.

**Comment by paul-f-maxson** [comment]
In broad strokes, what would this entail? It looks like all that is needed are some systematic tweaks to the rasi files. Is there anything else that would definitely need adjusted?

**Comment by adi1090x** [comment]
Depends on scaling, Can be done just edit the files.

> Everything is updated, Check the new config file, written from scratch.

**Comment by fiskhest** [comment]
Checked through the new config files, still unsure what must be done. Just trial and error modify the statically defined margin&padding px's?

When you say depends on scaling, do you mean DPI?

**Comment by adinhodovic** [comment]
> Checked through the new config files, still unsure what must be done. Just trial and error modify the statically defined margin&padding px's?
> 
> When you say depends on scaling, do you mean DPI?

```config.rasi
configuration {
/*---------- General setting ----------*/
 dpi: 220;
```
