### ISSUE TITLE
Any idea how to make powermenu full_circle circles more round?

### ISSUE THREAD

**Issue by iambeingtracked** [adi1090x/rofi#88]
I'm using a full_circle theme for a powermenu. But imho the circles which highlight the section you are on now using background_alt looks more like an oval than a circle. Is it possible to make them look more like a circle?

**Comment by renanrod4** [comment]
can you send the code here?
check the width and height of the circle, they must have the same value

**Comment by iambeingtracked** [comment]
Here's the full code, what do i need to change?: ```
/*
 *
 * Author  : Aditya Shakya
 * Mail    : adi1090x@gmail.com
 * Github  : @adi1090x
 * Twitter : @adi1090x
 *
 */

configuration {
	font:							"CaskaydiaCove Nerd Font 14";
    show-icons:                     false;
	icon-theme: 					"Papirus";
    drun-display-format:            "{name}";
    disable-history:                false;
	sidebar-mode: 					false;
}

@import "styles/colors.rasi"

window {
    transparency:                   "real";
    background-color:               @background;
    text-color:                     @foreground;
    border-radius:                  0px;
	width:							100%;
	height:							100%;
}

prompt {
    enabled: 						true;
    padding:                        1% 1% 1% 0%;
	background-color: 				@background-alt;
	text-color: 					@foreground;
}

textbox-prompt-colon {
	expand: 						false;
	str: 							"";
	background-color: 				@background-alt;
	text-color: 					@foreground;
    padding:                        1% 0.5% 1% 0.5%;
}

inputbar {
	children: 						[ textbox-prompt-colon, prompt ];
    background-color:               @background-alt;
    text-color:                     @foreground;
    expand:                         false;
    border:                  		0% 0.2% 0% 0.2%;
    border-radius:                  0% 100% 100% 0%;
    border-color:                  	@border;
    margin:                         0% 59.3% 0% 0%;
    padding:                        0.5%;
    position:                       center;
}

listview {
    background-color:               @background;
    margin:                         0% 0% 0% 0%;
    spacing:                        3%;
    cycle:                          true;
    dynamic:                        true;
    layout:                         horizontal;
}

mainbox {
    background-color:               @background;
    children:                       [ inputbar, listview ];
    spacing:                        5%;
    padding:                        32.50% 0% 0% 13.25%;
}

element {
    background-color:               @background-alt;
    text-color:                     @foreground;
    orientation:                    horizontal;
    border-radius:                  100%;
}

element-text {
    background-color: 				#00000000;
    text-color:       				inherit;
	font:							"feather 64";
    expand:                         true;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    margin:                         6.5% 4% 6.5% 4%;
}

element normal.urgent,
element alternate.urgent {
    background-color:               @urgent;
    text-color:                     @foreground;
    border-radius:                  0.2%;
}

element normal.active,
element alternate.active {
    background-color:               @background-alt;
    text-color:                     @foreground;
}

element selected {
    background-color:               @selected;
    text-color:                     @foreground;
    border:                  		0% 0.2% 0% 0%;
    border-radius:                  100%;
    border-color:                  	@border;
}

element selected.urgent {
    background-color:               @urgent;
    text-color:                     @foreground;
}

element selected.active {
    background-color:               @background-alt;
    color:                          @foreground;
}
```

**Comment by iambeingtracked** [comment]
I changed the font from feather to the font i always use and it worked just fine
