### ISSUE TITLE
scrot select mode gives ugly lines

### ISSUE THREAD

**Issue by ek234** [adi1090x/rofi#89]
Taking screenshots using scrot select mode (-s) causes weird lines as shown below.

![Screenshot_2022-02-21-15_1085x713](https://user-images.githubusercontent.com/71319388/155004808-ed16a537-aec9-4bf1-88a2-6cadbd5d6655.png)

This is quite irritating, especially because select is the mode I use the most.
Scrot recommends freezing the bg so that the lines do not appear.

If you want, I can patch this and make a PR.

**Comment by adi1090x** [comment]
That'll be fixed in few day, New Configs coming.
