### ISSUE TITLE
wierd separator in the option

### ISSUE THREAD

**Issue by seniorkiller** [adi1090x/rofi#92]
first time using this i notice the option button its uneven or look wierd

![2022-04-16-103841_1366x768_scrot](https://user-images.githubusercontent.com/77882062/163660120-35c5ff94-ab84-4fac-ae10-e95212500556.png)

![2022-04-16-101643_1366x768_scrot](https://user-images.githubusercontent.com/77882062/163660018-f5feece4-29cb-4dcb-8715-b00f55868804.png)

after playing around with the config rasi its appear that there's a separator like covering it
![2022-04-16-104128_1366x768_scrot](https://user-images.githubusercontent.com/77882062/163660200-4d86b121-b683-4a7f-90dc-4c073382025a.png)

this what i change in the config file
```
element {
    background-color:               @background-light;
    text-color:                     @foreground;
    /* orientation:                    vertical; */
    border-radius:                  12px;
    padding:    0px 0px 0px 3px;
}
```

**Comment by seniorkiller** [comment]
its the same with the android and menu

**Comment by adi1090x** [comment]
Everything is updated, Try new config files, written from scratch.
