### ISSUE TITLE
too much movement in the read me

### ISSUE THREAD

**Issue by CouldBeThis** [adi1090x/rofi#93]
I can't read the documentation because there is so much animations flashing everywhere. 

There are so many animations that it's not possible to scroll the page in such a way that they are out of view to read the text. 

If you want to show every possible permutation included, maybe a gallery or screenshot section or separate page would be better. Personally I am not getting much information from any of these screenshots, especially as there are 2 visible simultaneously, it is really chaotic. 

It would probably be easier to manage additions and changes that way too.

**Comment by adi1090x** [comment]
Hope that's fixed now.
