### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by amtoine** [adi1090x/rofi#94]
This is a pretty cool project and i was just wondering if it was dead or not :thinking: 

Cheers to everyone seeing this :wave: :yum:

**Comment by renanrod4** [comment]
adi1090x isn't messing with the project anymore, he's probably focusing more on archcraft

**Comment by a2n-s** [comment]
@renanrod4 
ooooh that might be it :yum: 
thanks for the info :+1: 

that's a bit sad not being able to contribute to the repo :shrug: 
maybe one day :open_mouth:

**Comment by frnco** [comment]
Well, the scripts are pretty easy to edit so I don't think it's that much of an issue.

I've been trying to make it less painful to deal with paths (Using a variable `="$(dirname $0)"` to replace those pesky `"$HOME/.config/rofi/applets/menu"` is pretty much the base of that, but I've also changed some stuff, mostly trying to isolate some stuff and reduce code duplication across scripts, and I'm probably going to change a lot more).

I'm also trying to make it easier to test different styles, and then there's the whole `usedcpu`/`usedram` scripts which bother me to no end for no particular reason (I just gave up on finding explanations and accepted that programmers are prone to having strong opinions regarding trivial stuff).

Maybe it would be a good idea to fork this and release those changes, but then again, everything's so simple and straightforward that it's probably unnecessary. After all,, to begin with, anyone using rofi probably has some scripting knowledge, especially if they're going as far as looking for things like this project. I still think it'd be better to have less duplicated code, I'd definitely prefer having a single script deal with all the paths mess, with the specific scripts only dealing with stuff that is actually relevant to them, but I'm not sure that's enough to justify managing a whole fork of this.

**Comment by amtoine** [comment]
> Well, the scripts are pretty easy to edit so I don't think it's that much of an issue.
> 
yup, right! :+1: 
i was more thinking about the issues and the PRs opened here, which do not get that much love at all :confused: 

> I've been trying to make it less painful to deal with paths (Using a variable `="$(dirname $0)"` to replace those pesky `"$HOME/.config/rofi/applets/menu"` is pretty much the base of that, but I've also changed some stuff, mostly trying to isolate some stuff and reduce code duplication across scripts, and I'm probably going to change a lot more).
> 
that is nice :yum: 

> Maybe it would be a good idea to fork this and release those changes, but then again, everything's so simple and straightforward that it's probably unnecessary. After all,, to begin with, anyone using rofi probably has some scripting knowledge, especially if they're going as far as looking for things like this project. I still think it'd be better to have less duplicated code, I'd definitely prefer having a single script deal with all the paths mess, with the specific scripts only dealing with stuff that is actually relevant to them, but I'm not sure that's enough to justify managing a whole fork of this.
>
that's the whole question indeed :thinking: 
do you know any maintained fork in the [list of forks](https://github.com/adi1090x/rofi/network/members)? :open_mouth:

**Comment by adi1090x** [comment]
Yes, It's alive and maintained. Updated it today.

**Comment by amtoine** [comment]
> Yes, It's alive and maintained. Updated it today.
>
ooooh that is super great news :star_struck: :relieved:
